project:
  type: website
extensions:
  - _extensions/thermomat
  - _extensions/thermomat-dividers
filters:
  - _extensions/thermomat-dividers/filters/divider.lua

profile:
  group:
    - [standard, posit, ehu-eu, ehu-es]
  default: standard

format:
  revealjs:
    theme: [default, styles.scss]
    slide-number: true
    hash: true
    transition: fade
    transition-speed: fast
    background-color: "#ffffff"
    width: 1600
    height: 900
    css:
      - _extensions/thermomat/ehu/styles/brand-core.css
      - styles/styles.scss
      - _extensions/thermomat-dividers/dividers.css
